name: JoeWilsonPhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7515
title: Sharing My Photography Passion With You !
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040301'
    - '#81644d'
    - '#534019'
    - '#c1a880'
    - '#e7e7e7'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
