typography_spectrum: 0.4055770926643163
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.46679829922504723
  lightness: 0.459230360109359
  saturation: 0.018567963736131787
  rhythmicContrast: 0.667369662085548
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5798253428656608
analytics:
  google: null
  facebook: null
  twitter: null
name: JoeWilsonPhotography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Joe Wilson Photography
purpose: []
