name: Joe Wilson Photography
favicon: null
layout_spectrum: 0.5798253428656608
typography_spectrum: 0.50554
title: The World Of Nature Through My Lens
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.46679829922504723
  lightness: 0.459230360109359
  saturation: 0.1875
  rhythmicContrast: 0.667369662085548
purpose: []
