name: Joe Wilson Photography
favicon: null
layout_spectrum: 0.31472
typography_spectrum: 0.50554
title: The World Of Nature Through My Lens
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
