name: JoeWilsonPhotography
favicon: null
layout_spectrum: 0.831407786346972
typography_spectrum: 0.4441091944463551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4000537402462214
  lightness: 0.04877576045691967
  saturation: 0.23258491465821862
  rhythmicContrast: 0.8467692120466381
purpose: []
