typography_spectrum: 0.50554
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37974
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Joe Wilson
  email: joe@joewilson.ca
name: Joe Wilson Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The World Of Nature Through My Lens
purpose: []
